# Generated by Django 2.0.7 on 2022-02-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220209_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='running_time',
            field=models.TimeField(null=True),
        ),
    ]
